### PR TITLE
project setup

### PR DESCRIPTION
**Pull request by jyotirmay123**
Committed base project setup with unit testing and REST endpoints configured.

### CODE REVIEW

**Review by shayansiddiqui — CHANGES_REQUESTED** [review]
Please change the default name to our project.

**Comment by jyotirmay123** [comment]
Modified the changes suggested. Have a look and do the needful. @shayansiddiqui

**Comment by syxolk** [comment]
- Are you sure you need all those dependencies? There is angular, react, graphql and mongoose?
- What are all those `copy`-files? You seem to have everything twice? (e.g. ".babelrc" and ".babelrc copy")
- I don't think its a good idea to auto-generate everything.

**Comment by csehlke** [comment]
I wanted to check it out and try running it, but I cannot find the branch; shouldn't there be a branch `Rostlab:projectSetup` or something like this?

**Comment by syxolk** [comment]
@csehlke He forked the repository. The branch is here: https://github.com/jyotirmay123/JS18_ProjectA_Group2/tree/master

@jyotirmay123 You don't need to fork the repo. Just create a branch here in this repo.

**Comment by jyotirmay123** [comment]
@syxolk oops. I did not notice that. I removed duplicate files now. Thank you for pointing out that.

I thought to have mongoose in place, if needed. If not, I can remove it later. 

Regarding graphql, it is a syntax that describes how to ask for data, and is generally used to load data from a server to a client. I thought may be useful for our user query task.

As this is a template base setup for MEAN stack applications, I did not notice before that react is there as usually react is not a part of MEAN. Anyway, React has been removed now.

Angular anyway, we will gonna have it.

I pushed the updated code again. Please check and let me know, everything is fine and merged it. 

@syxolk @shayansiddiqui

**Review by shayansiddiqui — APPROVED** [review]

**Comment by syxolk** [comment]
I don't like those project generators because you don't know what is actually happening. I hope you and your team know how to use most of those libraries.

**Pull request merged**
