### PR TITLE
new setup

### PR DESCRIPTION
**Pull request by jyotirmay123**
Re-created the entire setup from scratch to avoid unknown and unexpected errors which are hard to handle. 
Not using MEAN2 full fledged boilerplate code anymore. There are lots of thing manual here, but for now I think it's easy. 
Test for server and UI is enabled with coverage report for server. 
Rest endpoints are activated with cross origin resource sharing(CORS) enabled. 
Plotly is integrated and a demo graph with dummy data has been plotted. Please merge it.

### CODE REVIEW

**Review by syxolk — COMMENTED** [review]
- Why is it splitted into a server and a UI part?
- Why do you need socketio?

**Comment by jyotirmay123** [comment]
@syxolk , As I mentioned in slack. The reason behind  splitting UI and server below.
server and ui will be well separated from each other but connected via REST endpoints. Later only the UI part can be available for various client like mobile(android, ios) and desktop with server part untouched.
All backend work like NLP and data loading can be done in server and no overhead for client.

The socket.io thing, I forgot to removed as it was there in my previous project. Anyway, It is removed now.
Let me know, if you see any more discrepancies. Thanks.

**Comment by syxolk** [comment]
Splitting it up makes everything a bit more difficult but it's probably manageable. For example, we will have to spin up two app servers in Azure then.

What is your team saying? @shayansiddiqui @iraklitchedia @csehlke

**Comment by jyotirmay123** [comment]
@syxolk , I don't think it makes anything difficult, just that we need 2 server for now. 
@shayansiddiqui gave a suggestion to integrate angular-cli to the project and I did it. Now you can generate components by using angular-cli commands and it does the configuration for you. Plotly is already integrated. Please somebody merge it. @iraklitchedia

**Comment by iraklitchedia** [comment]
I think it's always good practice to split back end and front end.

**Review by iraklitchedia — APPROVED** [review]
Looks good

**Comment by jyotirmay123** [comment]
@iraklitchedia Thank youuu very much..

**Pull request merged**
